#!/usr/bin/env python3
"""Generate docs/ARIA2_RPC_WRAPPERS.md by introspecting aria2_ functions in core.py.

Usage:
    python scripts/gen_rpc_docs.py
"""

from __future__ import annotations

import ast
import inspect
import re
import sys
from pathlib import Path
from typing import Any

_SRC = Path(__file__).resolve().parents[1] / "src"
sys.path.insert(0, str(_SRC))

from aria_queue import aria2_rpc as _rpc_module
from aria_queue import core


def _extract_rpc_method(func_name: str, source: str) -> str | None:
    """Extract the aria2/system RPC method string from function source."""
    m = re.search(r'(?:aria_rpc|_rpc)\(\s*"((aria2|system)\.\w+)"', source)
    return m.group(1) if m else None


def _get_signature(func: Any) -> str:
    """Return a clean signature string."""
    sig = inspect.signature(func)
    params: list[str] = []
    for name, p in sig.parameters.items():
        if name in ("port", "timeout"):
            continue
        if p.default is inspect.Parameter.empty:
            params.append(f"{name}: {_format_annotation(p.annotation)}")
        else:
            params.append(
                f"{name}: {_format_annotation(p.annotation)} = {p.default!r}"
            )
    ret = sig.return_annotation
    ret_str = _format_annotation(ret) if ret is not inspect.Parameter.empty else "Any"
    return f"({', '.join(params)}) -> {ret_str}"


def _format_annotation(ann: Any) -> str:
    if ann is inspect.Parameter.empty:
        return "Any"
    if isinstance(ann, str):
        return ann
    if hasattr(ann, "__name__"):
        return ann.__name__
    return str(ann).replace("typing.", "")


def collect_wrappers() -> list[dict[str, Any]]:
    """Find all aria2_* functions and extract metadata."""
    wrappers: list[dict[str, Any]] = []
    for name in sorted(dir(_rpc_module)):
        if not name.startswith("aria2_"):
            continue
        func = getattr(_rpc_module, name)
        if not callable(func):
            continue
        try:
            source = inspect.getsource(func)
        except (OSError, TypeError):
            continue
        rpc_method = _extract_rpc_method(name, source)
        if not rpc_method:
            continue
        doc = (func.__doc__ or "").strip()
        sig = _get_signature(func)
        wrappers.append(
            {
                "name": name,
                "rpc_method": rpc_method,
                "signature": sig,
                "doc": doc,
                "category": _categorize(rpc_method),
            }
        )
    return wrappers


def _categorize(method: str) -> str:
    m = method.split(".", 1)[1] if "." in method else method
    if m.startswith("add"):
        return "Download Addition"
    if "pause" in m.lower() or "unpause" in m.lower():
        return "Pause / Resume"
    if m.startswith("remove") or m.startswith("forceRemove"):
        return "Remove"
    if m.startswith("tell") or m.startswith("get") and m not in (
        "getGlobalOption",
        "getGlobalStat",
        "getOption",
        "getVersion",
        "getSessionInfo",
    ):
        return "Status Query"
    if "Option" in m:
        return "Options"
    if m in ("changePosition", "changeUri"):
        return "Queue Management"
    if m in ("getGlobalStat",):
        return "Global Stats"
    if m in ("purgeDownloadResult",):
        return "Cleanup"
    if m in ("getVersion", "getSessionInfo", "saveSession", "shutdown", "forceShutdown"):
        return "Session / Lifecycle"
    if method.startswith("system."):
        return "System"
    return "Other"


def render_markdown(wrappers: list[dict[str, Any]]) -> str:
    lines: list[str] = []
    lines.append("# aria2 RPC Wrapper Functions Reference")
    lines.append("")
    lines.append(
        "> Auto-generated by `scripts/gen_rpc_docs.py` — do not edit manually."
    )
    lines.append(">")
    lines.append("> Regenerate: `python scripts/gen_rpc_docs.py`")
    lines.append("")
    lines.append(f"**aria2 version:** 1.37.0  ")
    lines.append(f"**Total wrappers:** {len(wrappers)}  ")
    lines.append(f"**Source:** `src/aria_queue/aria2_rpc.py`")
    lines.append("")

    # Summary table
    lines.append("## Summary")
    lines.append("")
    lines.append("| Wrapper | RPC Method | Category |")
    lines.append("|---|---|---|")
    for w in wrappers:
        lines.append(f"| `{w['name']}` | `{w['rpc_method']}` | {w['category']} |")
    lines.append("")

    # Grouped detail sections
    categories_order = [
        "Download Addition",
        "Pause / Resume",
        "Remove",
        "Status Query",
        "Options",
        "Queue Management",
        "Global Stats",
        "Cleanup",
        "Session / Lifecycle",
        "System",
        "Other",
    ]
    grouped: dict[str, list[dict[str, Any]]] = {}
    for w in wrappers:
        grouped.setdefault(w["category"], []).append(w)

    for cat in categories_order:
        items = grouped.get(cat)
        if not items:
            continue
        lines.append(f"## {cat}")
        lines.append("")
        for w in items:
            lines.append(f"### `{w['name']}`")
            lines.append("")
            lines.append(f"**RPC method:** `{w['rpc_method']}`  ")
            lines.append(f"**Signature:** `{w['name']}{w['signature']}`")
            if w["doc"]:
                lines.append("")
                lines.append(w["doc"])
            lines.append("")

    return "\n".join(lines) + "\n"


def main() -> None:
    wrappers = collect_wrappers()
    md = render_markdown(wrappers)
    out = Path(__file__).resolve().parents[1] / "docs" / "ARIA2_RPC_WRAPPERS.md"
    out.write_text(md, encoding="utf-8")
    print(f"Generated {out} ({len(wrappers)} wrappers)")


if __name__ == "__main__":
    main()
